name: unn_mobile
description: A mobile application for UNN Portal website
publish_to: 'none'


version: 0.2.3+229


environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  share_plus: ^10.0.2
  webview_flutter: ^4.9.0
  flutter_secure_storage: ^9.2.2
  http: ^1.1.0
  injector: ^4.0.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  flutter_svg: any
  connectivity_plus: ^6.0.5
  device_calendar: 4.3.3-20240801
  icalendar_parser: ^2.0.0
  permission_handler_android: ^12.0.1
  permission_handler_apple: ^9.2.0
  permission_handler_platform_interface: ^4.0.0
  scroll_to_index: ^3.0.1
  flutter_native_splash: ^2.3.6
  flutter_cache_manager: ^3.3.1
  flutter_changed:
    path: ./modules/flutter_changed/
  cached_network_image: ^3.3.1
  firebase_core: ^3.5.0
  firebase_crashlytics: ^4.1.2
  firebase_analytics: ^11.3.2
  url_launcher: ^6.2.5
  async: ^2.11.0
  flutter_bbcode:
    path: ./modules/flutter_bbcode/
  bbob_dart: 
    path: ./modules/flutter_bbcode/bbob_dart/
  html_unescape: ^2.0.0
  path_provider: ^2.1.3
  open_filex: ^4.4.0
  path: 
  extended_image: ^8.2.0
  package_info_plus: ^8.0.2
  go_router: ^14.2.7
  event: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/authors/
    - assets/images/reactions/
    - assets/ca/
    - assets/html/


  fonts:
    - family: LetoSans
      fonts:
        - asset: assets/fonts/LetoSans-Bold.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 19
  remove_alpha_ios: true
