name: unn_mobile
description: A mobile application for UNN Portal website
publish_to: 'none'
version: 0.1.2+8

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  http: ^1.1.0
  injector: ^3.0.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  flutter_svg: any
  connectivity_plus: ^5.0.1
  device_calendar: ^4.3.2
  icalendar_parser: ^2.0.0
  permission_handler_android: ^12.0.1
  permission_handler_apple: ^9.2.0
  permission_handler_platform_interface: ^4.0.0
  scroll_to_index: ^3.0.1
  flutter_native_splash: ^2.3.6
  flutter_cache_manager: ^3.3.1
  flutter_changed:
    path: ./flutter_changed/
  cached_network_image: ^3.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/new_year_logo.png
    - assets/images/auth-logo.svg
    - assets/images/authors/dmitry.png
    - assets/images/authors/vitaly.png
    - assets/images/authors/michail.png
    - assets/images/authors/darya.png
    - assets/images/authors/andrew.png

  fonts:
    - family: LetoSans
      fonts:
        - asset: assets/fonts/LetoSans-Bold.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 19
  remove_alpha_ios: true

