name: unn_mobile
description: A mobile application for UNN Portal website
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  http: ^1.1.0
  injector: ^3.0.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  flutter_svg: any
  connectivity_plus: ^5.0.1
  device_calendar: ^4.3.2
  icalendar_parser: ^2.0.0
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/auth-logo.svg
    
  fonts:
    - family: LetoSans
      fonts:
        - asset: assets/fonts/LetoSans-Bold.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
