# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter Analyze
run-name: Analyze formatting in PR ${{ github.event.number }}

on:
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:
    
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check-format:
    if: github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      # - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'
          cache: true
      - name: get firebase config
        env:
          CONFIG: ${{ vars.CLEAN_FIREBASE_CONFIG }}
        run: printf '%s' "$CONFIG" > ./lib/firebase_options.dart
      - name: Install dependencies
        run: flutter pub get
      - name: Verify formatting
        id: verifying
        continue-on-error: true
        run: |
          cp -r lib/ lib_original/
          dart format ./lib/
      - name: display diff
        if: steps.verifying.outcome == 'failure'
        run: |
          diff -u lib_original/ lib/
          rm -rf lib_original/
      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: flutter analyze lib
      - name: fail
        if: steps.verifying.outcome == 'failure'
        run: exit 1
